#############################################################################
# Makefile for building: daa4-arm-gui
# Generated by qmake (1.07a) (Qt 3.3.8) on: Mon Aug  4 19:45:09 2014
# Project:  daa4-arm-gui.pro
# Template: app
# Command: $(QMAKE) -spec /home/kangqi/git/repos/daa4-arm-gui/mkspecs/arm/ -o Makefile daa4-arm-gui.pro
#############################################################################

####### Compiler, tools and options

CC       = arm-linux-gcc
CXX      = arm-linux-g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -D__ARM__ -O2  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -D__ARM__ -DQWS -fno-exceptions -fno-rtti -O2  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/home/kangqi/git/repos/daa4-arm-gui/mkspecs/arm -I. -I. -Iinclude -Icommon -I$(QTDIR)/include
LINK     = arm-linux-g++
LFLAGS   = -L./depend  -Wl,-rpath,$(QTDIR)/lib
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -lmxml -lrt -lsqlite3 -lqte-mt
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -R
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = common/rkcalib.h \
		common/rkcom.h \
		common/rkfifo.h \
		common/rkshm.h \
		common/rkusb.h \
		include/rkapp.h \
		include/rkbtnkey.h \
		include/rkbtnsw.h \
		include/rkckbox.h \
		include/rkclr.h \
		include/rkdlg.h \
		include/rkdlgfml.h \
		include/rkdlgfmlsel.h \
		include/rkdlgkb.h \
		include/rkdlgsel.h \
		include/rkfltip.h \
		include/rkfmaicalib.h \
		include/rkfmcalib.h \
		include/rkfmexp.h \
		include/rkfminfo.h \
		include/rkfmpri.h \
		include/rkfmpw.h \
		include/rkfmqrymsg.h \
		include/rkfmqryrtd.h \
		include/rkfmscrcalib.h \
		include/rkfmset.h \
		include/rkfmview.h \
		include/rkfrm.h \
		include/rkhisto.h \
		include/rkifaceoper.h \
		include/rkinit.h \
		include/rklnedit.h \
		include/rkplotter.h \
		include/rksetanalog.h \
		include/rksetcom.h \
		include/rksetdio.h \
		include/rksetdo.h \
		include/rksetnet.h \
		include/rksetsys.h \
		include/rksetvar.h \
		include/rktabwgt.h \
		include/rktbl.h \
		include/rktrdmnt.h \
		include/rktrdmsg.h \
		include/rktype.h \
		include/rkxmloper.h \
		include/rkxmlproc.h \
		include/sqlite3.h \
		include/tslib.h \
		ui/rkmsgview.ui.h \
		mkspecs/arm/qplatformdefs.h \
		mkspecs/x86/qplatformdefs.h
SOURCES = common/rkcalib.c \
		common/rkfifo.c \
		common/rkshm.c \
		common/rkusb.c \
		src/main.cpp \
		src/rkapp.cpp \
		src/rkbtnkey.cpp \
		src/rkbtnsw.cpp \
		src/rkckbox.cpp \
		src/rkclr.cpp \
		src/rkdlg.cpp \
		src/rkdlgfml.cpp \
		src/rkdlgfmlsel.cpp \
		src/rkdlgkb.cpp \
		src/rkdlgsel.cpp \
		src/rkfltip.cpp \
		src/rkfmaicalib.cpp \
		src/rkfmcalib.cpp \
		src/rkfmexp.cpp \
		src/rkfminfo.cpp \
		src/rkfmpri.cpp \
		src/rkfmpw.cpp \
		src/rkfmqrymsg.cpp \
		src/rkfmqryrtd.cpp \
		src/rkfmscrcalib.cpp \
		src/rkfmset.cpp \
		src/rkfmview.cpp \
		src/rkfrm.cpp \
		src/rkhisto.cpp \
		src/rkifaceoper.cpp \
		src/rkinit.cpp \
		src/rklnedit.cpp \
		src/rkplotter.cpp \
		src/rksetanalog.cpp \
		src/rksetcom.cpp \
		src/rksetdio.cpp \
		src/rksetdo.cpp \
		src/rksetnet.cpp \
		src/rksetsys.cpp \
		src/rksetvar.cpp \
		src/rktabwgt.cpp \
		src/rktrdmnt.cpp \
		src/rktrdmsg.cpp \
		src/rkxmloper.cpp \
		src/rkxmlproc.cpp
OBJECTS = rkcalib.o \
		rkfifo.o \
		rkshm.o \
		rkusb.o \
		main.o \
		rkapp.o \
		rkbtnkey.o \
		rkbtnsw.o \
		rkckbox.o \
		rkclr.o \
		rkdlg.o \
		rkdlgfml.o \
		rkdlgfmlsel.o \
		rkdlgkb.o \
		rkdlgsel.o \
		rkfltip.o \
		rkfmaicalib.o \
		rkfmcalib.o \
		rkfmexp.o \
		rkfminfo.o \
		rkfmpri.o \
		rkfmpw.o \
		rkfmqrymsg.o \
		rkfmqryrtd.o \
		rkfmscrcalib.o \
		rkfmset.o \
		rkfmview.o \
		rkfrm.o \
		rkhisto.o \
		rkifaceoper.o \
		rkinit.o \
		rklnedit.o \
		rkplotter.o \
		rksetanalog.o \
		rksetcom.o \
		rksetdio.o \
		rksetdo.o \
		rksetnet.o \
		rksetsys.o \
		rksetvar.o \
		rktabwgt.o \
		rktrdmnt.o \
		rktrdmsg.o \
		rkxmloper.o \
		rkxmlproc.o \
		rkmsgview.o
FORMS = ui/rkmsgview.ui
UICDECLS = ui/rkmsgview.h
UICIMPLS = ui/rkmsgview.cpp
SRCMOC   = include/moc_rkapp.cpp \
		include/moc_rkbtnkey.cpp \
		include/moc_rkbtnsw.cpp \
		include/moc_rkckbox.cpp \
		include/moc_rkdlg.cpp \
		include/moc_rkdlgfml.cpp \
		include/moc_rkdlgfmlsel.cpp \
		include/moc_rkdlgkb.cpp \
		include/moc_rkdlgsel.cpp \
		include/moc_rkfmaicalib.cpp \
		include/moc_rkfmcalib.cpp \
		include/moc_rkfmexp.cpp \
		include/moc_rkfminfo.cpp \
		include/moc_rkfmpri.cpp \
		include/moc_rkfmpw.cpp \
		include/moc_rkfmqrymsg.cpp \
		include/moc_rkfmqryrtd.cpp \
		include/moc_rkfmscrcalib.cpp \
		include/moc_rkfmset.cpp \
		include/moc_rkfmview.cpp \
		include/moc_rkfrm.cpp \
		include/moc_rkhisto.cpp \
		include/moc_rklnedit.cpp \
		include/moc_rksetanalog.cpp \
		include/moc_rksetcom.cpp \
		include/moc_rksetdio.cpp \
		include/moc_rksetdo.cpp \
		include/moc_rksetnet.cpp \
		include/moc_rksetsys.cpp \
		include/moc_rksetvar.cpp \
		include/moc_rktabwgt.cpp \
		include/moc_rktrdmnt.cpp \
		include/moc_rktrdmsg.cpp \
		ui/moc_rkmsgview.cpp
OBJMOC = moc_rkapp.o \
		moc_rkbtnkey.o \
		moc_rkbtnsw.o \
		moc_rkckbox.o \
		moc_rkdlg.o \
		moc_rkdlgfml.o \
		moc_rkdlgfmlsel.o \
		moc_rkdlgkb.o \
		moc_rkdlgsel.o \
		moc_rkfmaicalib.o \
		moc_rkfmcalib.o \
		moc_rkfmexp.o \
		moc_rkfminfo.o \
		moc_rkfmpri.o \
		moc_rkfmpw.o \
		moc_rkfmqrymsg.o \
		moc_rkfmqryrtd.o \
		moc_rkfmscrcalib.o \
		moc_rkfmset.o \
		moc_rkfmview.o \
		moc_rkfrm.o \
		moc_rkhisto.o \
		moc_rklnedit.o \
		moc_rksetanalog.o \
		moc_rksetcom.o \
		moc_rksetdio.o \
		moc_rksetdo.o \
		moc_rksetnet.o \
		moc_rksetsys.o \
		moc_rksetvar.o \
		moc_rktabwgt.o \
		moc_rktrdmnt.o \
		moc_rktrdmsg.o \
		moc_rkmsgview.o
DIST	   = daa4-arm-gui.pro
QMAKE_TARGET = daa4-arm-gui
DESTDIR  = 
TARGET   = daa4-arm-gui

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: daa4-arm-gui.pro  /home/kangqi/git/repos/daa4-arm-gui/mkspecs/arm/qmake.conf /usr/local/arm/qt3-embedded/lib/libqte-mt.prl
	$(QMAKE) -spec /home/kangqi/git/repos/daa4-arm-gui/mkspecs/arm/ -o Makefile daa4-arm-gui.pro
qmake: 
	@$(QMAKE) -spec /home/kangqi/git/repos/daa4-arm-gui/mkspecs/arm/ -o Makefile daa4-arm-gui.pro

dist: 
	@mkdir -p .tmp/daa4-arm-gui && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/daa4-arm-gui/ && $(COPY_FILE) --parents ui/rkmsgview.ui.h .tmp/daa4-arm-gui/ && ( cd `dirname .tmp/daa4-arm-gui` && $(TAR) daa4-arm-gui.tar daa4-arm-gui && $(GZIP) daa4-arm-gui.tar ) && $(MOVE) `dirname .tmp/daa4-arm-gui`/daa4-arm-gui.tar.gz . && $(DEL_FILE) -r .tmp/daa4-arm-gui

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

rkcalib.o: common/rkcalib.c include/rktype.h \
		common/rkcalib.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rkcalib.o common/rkcalib.c

rkfifo.o: common/rkfifo.c common/rkfifo.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rkfifo.o common/rkfifo.c

rkshm.o: common/rkshm.c common/rkcom.h \
		common/rkshm.h \
		common/rkfifo.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rkshm.o common/rkshm.c

rkusb.o: common/rkusb.c common/rkusb.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rkusb.o common/rkusb.c

main.o: src/main.cpp include/rktype.h \
		common/rkshm.h \
		include/rkinit.h \
		include/rkfmpri.h \
		include/rktrdmnt.h \
		include/rkapp.h \
		include/rkfmscrcalib.h \
		common/rkcom.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h \
		include/tslib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

rkapp.o: src/rkapp.cpp include/rkapp.h \
		include/rkclr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkapp.o src/rkapp.cpp

rkbtnkey.o: src/rkbtnkey.cpp include/rkbtnkey.h \
		include/rkclr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkbtnkey.o src/rkbtnkey.cpp

rkbtnsw.o: src/rkbtnsw.cpp include/rktype.h \
		include/rkbtnsw.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkbtnsw.o src/rkbtnsw.cpp

rkckbox.o: src/rkckbox.cpp include/rktype.h \
		include/rkckbox.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkckbox.o src/rkckbox.cpp

rkclr.o: src/rkclr.cpp include/rkclr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkclr.o src/rkclr.cpp

rkdlg.o: src/rkdlg.cpp include/rkdlg.h \
		include/rkclr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkdlg.o src/rkdlg.cpp

rkdlgfml.o: src/rkdlgfml.cpp include/rkdlgfml.h \
		include/rklnedit.h \
		include/rkdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkdlgfml.o src/rkdlgfml.cpp

rkdlgfmlsel.o: src/rkdlgfmlsel.cpp include/rkdlgfmlsel.h \
		include/rkdlgfml.h \
		include/rkdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkdlgfmlsel.o src/rkdlgfmlsel.cpp

rkdlgkb.o: src/rkdlgkb.cpp include/rkclr.h \
		include/rkdlgkb.h \
		include/rkbtnkey.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkdlgkb.o src/rkdlgkb.cpp

rkdlgsel.o: src/rkdlgsel.cpp include/rkdlgsel.h \
		include/rkclr.h \
		include/rkckbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkdlgsel.o src/rkdlgsel.cpp

rkfltip.o: src/rkfltip.cpp include/rkfltip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfltip.o src/rkfltip.cpp

rkfmaicalib.o: src/rkfmaicalib.cpp include/rkfmaicalib.h \
		include/rkclr.h \
		common/rkcalib.h \
		include/rkckbox.h \
		common/rkcom.h \
		include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfmaicalib.o src/rkfmaicalib.cpp

rkfmcalib.o: src/rkfmcalib.cpp include/rkfmcalib.h \
		include/rkfmscrcalib.h \
		include/rkfmaicalib.h \
		include/rkfrm.h \
		include/rktype.h \
		include/rkdlgkb.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/tslib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfmcalib.o src/rkfmcalib.cpp

rkfmexp.o: src/rkfmexp.cpp include/rktype.h \
		common/rkusb.h \
		include/rkfmexp.h \
		include/rkclr.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfmexp.o src/rkfmexp.cpp

rkfminfo.o: src/rkfminfo.cpp include/rktype.h \
		common/rkshm.h \
		include/rkfminfo.h \
		include/rklnedit.h \
		include/rkdlgsel.h \
		common/rkcom.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfminfo.o src/rkfminfo.cpp

rkfmpri.o: src/rkfmpri.cpp ui/rkmsgview.h \
		include/rkfmpri.h \
		include/rkfmset.h \
		include/rkfmview.h \
		include/rkfmexp.h \
		include/rkfmqrymsg.h \
		include/rkfmqryrtd.h \
		include/rkfminfo.h \
		include/rkfmpw.h \
		include/rktrdmsg.h \
		include/rkfmscrcalib.h \
		include/rkfrm.h \
		include/rkdlgkb.h \
		include/rktype.h \
		common/rkshm.h \
		common/rkcom.h \
		include/sqlite3.h \
		include/tslib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfmpri.o src/rkfmpri.cpp

rkfmpw.o: src/rkfmpw.cpp include/rkfmpw.h \
		include/rkfrm.h \
		include/rklnedit.h \
		include/rkxmloper.h \
		include/rkdlgkb.h \
		include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfmpw.o src/rkfmpw.cpp

rkfmqrymsg.o: src/rkfmqrymsg.cpp ui/rkmsgview.h \
		include/rktbl.h \
		include/rkclr.h \
		include/rktype.h \
		include/rkfmqrymsg.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfmqrymsg.o src/rkfmqrymsg.cpp

rkfmqryrtd.o: src/rkfmqryrtd.cpp include/rkclr.h \
		include/rktype.h \
		include/rktbl.h \
		include/rkfmqryrtd.h \
		include/rkdlgsel.h \
		include/rklnedit.h \
		include/rkckbox.h \
		include/rkxmloper.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfmqryrtd.o src/rkfmqryrtd.cpp

rkfmscrcalib.o: src/rkfmscrcalib.cpp include/rkfmscrcalib.h \
		include/rkclr.h \
		include/tslib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfmscrcalib.o src/rkfmscrcalib.cpp

rkfmset.o: src/rkfmset.cpp include/rkfmset.h \
		include/rksetanalog.h \
		include/rksetsys.h \
		include/rksetnet.h \
		include/rksetdio.h \
		include/rksetcom.h \
		include/rkfmcalib.h \
		include/rksetdo.h \
		include/rksetvar.h \
		include/rkfrm.h \
		include/rkdlgkb.h \
		include/rktype.h \
		include/rklnedit.h \
		include/rkckbox.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfmset.o src/rkfmset.cpp

rkfmview.o: src/rkfmview.cpp include/rktype.h \
		include/rkfmview.h \
		include/rkhisto.h \
		include/rkplotter.h \
		include/rkclr.h \
		include/rktbl.h \
		include/rktabwgt.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfmview.o src/rkfmview.cpp

rkfrm.o: src/rkfrm.cpp include/rkfrm.h \
		include/rktype.h \
		include/rkclr.h \
		include/rkdlgkb.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkfrm.o src/rkfrm.cpp

rkhisto.o: src/rkhisto.cpp include/rkhisto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkhisto.o src/rkhisto.cpp

rkifaceoper.o: src/rkifaceoper.cpp include/rkifaceoper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkifaceoper.o src/rkifaceoper.cpp

rkinit.o: src/rkinit.cpp include/rkinit.h \
		include/rktype.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkinit.o src/rkinit.cpp

rklnedit.o: src/rklnedit.cpp include/rklnedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rklnedit.o src/rklnedit.cpp

rkplotter.o: src/rkplotter.cpp include/rkplotter.h \
		include/rkclr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkplotter.o src/rkplotter.cpp

rksetanalog.o: src/rksetanalog.cpp include/rksetanalog.h \
		include/rkdlgsel.h \
		include/rklnedit.h \
		include/rkdlgfmlsel.h \
		include/rkxmloper.h \
		include/rkckbox.h \
		include/rkfrm.h \
		include/rktype.h \
		include/rkdlgkb.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkdlg.h \
		include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rksetanalog.o src/rksetanalog.cpp

rksetcom.o: src/rksetcom.cpp include/rktype.h \
		include/rksetcom.h \
		include/rklnedit.h \
		include/rkxmloper.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h \
		include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rksetcom.o src/rksetcom.cpp

rksetdio.o: src/rksetdio.cpp include/rktype.h \
		include/rksetdio.h \
		include/rklnedit.h \
		include/rkxmloper.h \
		include/rkckbox.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h \
		include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rksetdio.o src/rksetdio.cpp

rksetdo.o: src/rksetdo.cpp include/rktype.h \
		include/rksetdo.h \
		include/rklnedit.h \
		include/rkbtnsw.h \
		include/rkxmloper.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h \
		include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rksetdo.o src/rksetdo.cpp

rksetnet.o: src/rksetnet.cpp include/rktype.h \
		include/rksetnet.h \
		include/rklnedit.h \
		include/rkxmloper.h \
		include/rkfltip.h \
		include/rkifaceoper.h \
		include/rkckbox.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h \
		include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rksetnet.o src/rksetnet.cpp

rksetsys.o: src/rksetsys.cpp include/rktype.h \
		include/rksetsys.h \
		include/rklnedit.h \
		include/rkdlgsel.h \
		include/rkxmloper.h \
		include/rkckbox.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h \
		include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rksetsys.o src/rksetsys.cpp

rksetvar.o: src/rksetvar.cpp include/rktype.h \
		include/rksetvar.h \
		include/rkdlgsel.h \
		include/rkdlgfmlsel.h \
		include/rklnedit.h \
		include/rkxmloper.h \
		include/rkckbox.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkfrm.h \
		include/rkdlgkb.h \
		include/rkdlg.h \
		include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rksetvar.o src/rksetvar.cpp

rktabwgt.o: src/rktabwgt.cpp include/rktabwgt.h \
		include/rkclr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rktabwgt.o src/rktabwgt.cpp

rktrdmnt.o: src/rktrdmnt.cpp include/rktrdmnt.h \
		include/tslib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rktrdmnt.o src/rktrdmnt.cpp

rktrdmsg.o: src/rktrdmsg.cpp include/rktrdmsg.h \
		include/rktype.h \
		common/rkshm.h \
		common/rkcom.h \
		include/sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rktrdmsg.o src/rktrdmsg.cpp

rkxmloper.o: src/rkxmloper.cpp include/rktype.h \
		include/rkxmloper.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h \
		include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkxmloper.o src/rkxmloper.cpp

rkxmlproc.o: src/rkxmlproc.cpp include/rkxmlproc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkxmlproc.o src/rkxmlproc.cpp

ui/rkmsgview.h: ui/rkmsgview.ui include/sqlite3.h \
		common/rkcom.h
	$(UIC) ui/rkmsgview.ui -o ui/rkmsgview.h

ui/rkmsgview.cpp: ui/rkmsgview.h ui/rkmsgview.ui ui/rkmsgview.ui.h include/sqlite3.h \
		common/rkcom.h
	$(UIC) ui/rkmsgview.ui -i rkmsgview.h -o ui/rkmsgview.cpp

rkmsgview.o: ui/rkmsgview.cpp include/rkclr.h \
		include/rktype.h \
		ui/rkmsgview.ui.h \
		ui/rkmsgview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rkmsgview.o ui/rkmsgview.cpp

moc_rkapp.o: include/moc_rkapp.cpp  include/rkapp.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkapp.o include/moc_rkapp.cpp

moc_rkbtnkey.o: include/moc_rkbtnkey.cpp  include/rkbtnkey.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkbtnkey.o include/moc_rkbtnkey.cpp

moc_rkbtnsw.o: include/moc_rkbtnsw.cpp  include/rkbtnsw.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkbtnsw.o include/moc_rkbtnsw.cpp

moc_rkckbox.o: include/moc_rkckbox.cpp  include/rkckbox.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkckbox.o include/moc_rkckbox.cpp

moc_rkdlg.o: include/moc_rkdlg.cpp  include/rkdlg.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkdlg.o include/moc_rkdlg.cpp

moc_rkdlgfml.o: include/moc_rkdlgfml.cpp  include/rkdlgfml.h include/rkdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkdlgfml.o include/moc_rkdlgfml.cpp

moc_rkdlgfmlsel.o: include/moc_rkdlgfmlsel.cpp  include/rkdlgfmlsel.h include/rkdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkdlgfmlsel.o include/moc_rkdlgfmlsel.cpp

moc_rkdlgkb.o: include/moc_rkdlgkb.cpp  include/rkdlgkb.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkdlgkb.o include/moc_rkdlgkb.cpp

moc_rkdlgsel.o: include/moc_rkdlgsel.cpp  include/rkdlgsel.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkdlgsel.o include/moc_rkdlgsel.cpp

moc_rkfmaicalib.o: include/moc_rkfmaicalib.cpp  include/rkfmaicalib.h common/rkcom.h \
		include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfmaicalib.o include/moc_rkfmaicalib.cpp

moc_rkfmcalib.o: include/moc_rkfmcalib.cpp  include/rkfmcalib.h include/rkfrm.h \
		include/rktype.h \
		include/rkdlgkb.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfmcalib.o include/moc_rkfmcalib.cpp

moc_rkfmexp.o: include/moc_rkfmexp.cpp  include/rkfmexp.h include/rkfrm.h \
		include/sqlite3.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfmexp.o include/moc_rkfmexp.cpp

moc_rkfminfo.o: include/moc_rkfminfo.cpp  include/rkfminfo.h include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfminfo.o include/moc_rkfminfo.cpp

moc_rkfmpri.o: include/moc_rkfmpri.cpp  include/rkfmpri.h include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfmpri.o include/moc_rkfmpri.cpp

moc_rkfmpw.o: include/moc_rkfmpw.cpp  include/rkfmpw.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfmpw.o include/moc_rkfmpw.cpp

moc_rkfmqrymsg.o: include/moc_rkfmqrymsg.cpp  include/rkfmqrymsg.h include/rkfrm.h \
		include/sqlite3.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfmqrymsg.o include/moc_rkfmqrymsg.cpp

moc_rkfmqryrtd.o: include/moc_rkfmqryrtd.cpp  include/rkfmqryrtd.h include/sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfmqryrtd.o include/moc_rkfmqryrtd.cpp

moc_rkfmscrcalib.o: include/moc_rkfmscrcalib.cpp  include/rkfmscrcalib.h include/tslib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfmscrcalib.o include/moc_rkfmscrcalib.cpp

moc_rkfmset.o: include/moc_rkfmset.cpp  include/rkfmset.h include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfmset.o include/moc_rkfmset.cpp

moc_rkfmview.o: include/moc_rkfmview.cpp  include/rkfmview.h include/rktype.h \
		include/rkfrm.h \
		common/rkshm.h \
		common/rkcom.h \
		include/sqlite3.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfmview.o include/moc_rkfmview.cpp

moc_rkfrm.o: include/moc_rkfrm.cpp  include/rkfrm.h include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkfrm.o include/moc_rkfrm.cpp

moc_rkhisto.o: include/moc_rkhisto.cpp  include/rkhisto.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkhisto.o include/moc_rkhisto.cpp

moc_rklnedit.o: include/moc_rklnedit.cpp  include/rklnedit.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rklnedit.o include/moc_rklnedit.cpp

moc_rksetanalog.o: include/moc_rksetanalog.cpp  include/rksetanalog.h include/rkfrm.h \
		include/rktype.h \
		include/rklnedit.h \
		include/rkckbox.h \
		include/rkdlgkb.h \
		common/rkcom.h \
		common/rkshm.h \
		include/sqlite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rksetanalog.o include/moc_rksetanalog.cpp

moc_rksetcom.o: include/moc_rksetcom.cpp  include/rksetcom.h include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rksetcom.o include/moc_rksetcom.cpp

moc_rksetdio.o: include/moc_rksetdio.cpp  include/rksetdio.h include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rksetdio.o include/moc_rksetdio.cpp

moc_rksetdo.o: include/moc_rksetdo.cpp  include/rksetdo.h include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rksetdo.o include/moc_rksetdo.cpp

moc_rksetnet.o: include/moc_rksetnet.cpp  include/rksetnet.h include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rksetnet.o include/moc_rksetnet.cpp

moc_rksetsys.o: include/moc_rksetsys.cpp  include/rksetsys.h include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rksetsys.o include/moc_rksetsys.cpp

moc_rksetvar.o: include/moc_rksetvar.cpp  include/rksetvar.h include/rkfrm.h \
		include/rkdlgkb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rksetvar.o include/moc_rksetvar.cpp

moc_rktabwgt.o: include/moc_rktabwgt.cpp  include/rktabwgt.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rktabwgt.o include/moc_rktabwgt.cpp

moc_rktrdmnt.o: include/moc_rktrdmnt.cpp  include/rktrdmnt.h include/tslib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rktrdmnt.o include/moc_rktrdmnt.cpp

moc_rktrdmsg.o: include/moc_rktrdmsg.cpp  include/rktrdmsg.h common/rkshm.h \
		common/rkcom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rktrdmsg.o include/moc_rktrdmsg.cpp

moc_rkmsgview.o: ui/moc_rkmsgview.cpp  ui/rkmsgview.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rkmsgview.o ui/moc_rkmsgview.cpp

include/moc_rkapp.cpp: $(MOC) include/rkapp.h
	$(MOC) include/rkapp.h -o include/moc_rkapp.cpp

include/moc_rkbtnkey.cpp: $(MOC) include/rkbtnkey.h
	$(MOC) include/rkbtnkey.h -o include/moc_rkbtnkey.cpp

include/moc_rkbtnsw.cpp: $(MOC) include/rkbtnsw.h
	$(MOC) include/rkbtnsw.h -o include/moc_rkbtnsw.cpp

include/moc_rkckbox.cpp: $(MOC) include/rkckbox.h
	$(MOC) include/rkckbox.h -o include/moc_rkckbox.cpp

include/moc_rkdlg.cpp: $(MOC) include/rkdlg.h
	$(MOC) include/rkdlg.h -o include/moc_rkdlg.cpp

include/moc_rkdlgfml.cpp: $(MOC) include/rkdlgfml.h
	$(MOC) include/rkdlgfml.h -o include/moc_rkdlgfml.cpp

include/moc_rkdlgfmlsel.cpp: $(MOC) include/rkdlgfmlsel.h
	$(MOC) include/rkdlgfmlsel.h -o include/moc_rkdlgfmlsel.cpp

include/moc_rkdlgkb.cpp: $(MOC) include/rkdlgkb.h
	$(MOC) include/rkdlgkb.h -o include/moc_rkdlgkb.cpp

include/moc_rkdlgsel.cpp: $(MOC) include/rkdlgsel.h
	$(MOC) include/rkdlgsel.h -o include/moc_rkdlgsel.cpp

include/moc_rkfmaicalib.cpp: $(MOC) include/rkfmaicalib.h
	$(MOC) include/rkfmaicalib.h -o include/moc_rkfmaicalib.cpp

include/moc_rkfmcalib.cpp: $(MOC) include/rkfmcalib.h
	$(MOC) include/rkfmcalib.h -o include/moc_rkfmcalib.cpp

include/moc_rkfmexp.cpp: $(MOC) include/rkfmexp.h
	$(MOC) include/rkfmexp.h -o include/moc_rkfmexp.cpp

include/moc_rkfminfo.cpp: $(MOC) include/rkfminfo.h
	$(MOC) include/rkfminfo.h -o include/moc_rkfminfo.cpp

include/moc_rkfmpri.cpp: $(MOC) include/rkfmpri.h
	$(MOC) include/rkfmpri.h -o include/moc_rkfmpri.cpp

include/moc_rkfmpw.cpp: $(MOC) include/rkfmpw.h
	$(MOC) include/rkfmpw.h -o include/moc_rkfmpw.cpp

include/moc_rkfmqrymsg.cpp: $(MOC) include/rkfmqrymsg.h
	$(MOC) include/rkfmqrymsg.h -o include/moc_rkfmqrymsg.cpp

include/moc_rkfmqryrtd.cpp: $(MOC) include/rkfmqryrtd.h
	$(MOC) include/rkfmqryrtd.h -o include/moc_rkfmqryrtd.cpp

include/moc_rkfmscrcalib.cpp: $(MOC) include/rkfmscrcalib.h
	$(MOC) include/rkfmscrcalib.h -o include/moc_rkfmscrcalib.cpp

include/moc_rkfmset.cpp: $(MOC) include/rkfmset.h
	$(MOC) include/rkfmset.h -o include/moc_rkfmset.cpp

include/moc_rkfmview.cpp: $(MOC) include/rkfmview.h
	$(MOC) include/rkfmview.h -o include/moc_rkfmview.cpp

include/moc_rkfrm.cpp: $(MOC) include/rkfrm.h
	$(MOC) include/rkfrm.h -o include/moc_rkfrm.cpp

include/moc_rkhisto.cpp: $(MOC) include/rkhisto.h
	$(MOC) include/rkhisto.h -o include/moc_rkhisto.cpp

include/moc_rklnedit.cpp: $(MOC) include/rklnedit.h
	$(MOC) include/rklnedit.h -o include/moc_rklnedit.cpp

include/moc_rksetanalog.cpp: $(MOC) include/rksetanalog.h
	$(MOC) include/rksetanalog.h -o include/moc_rksetanalog.cpp

include/moc_rksetcom.cpp: $(MOC) include/rksetcom.h
	$(MOC) include/rksetcom.h -o include/moc_rksetcom.cpp

include/moc_rksetdio.cpp: $(MOC) include/rksetdio.h
	$(MOC) include/rksetdio.h -o include/moc_rksetdio.cpp

include/moc_rksetdo.cpp: $(MOC) include/rksetdo.h
	$(MOC) include/rksetdo.h -o include/moc_rksetdo.cpp

include/moc_rksetnet.cpp: $(MOC) include/rksetnet.h
	$(MOC) include/rksetnet.h -o include/moc_rksetnet.cpp

include/moc_rksetsys.cpp: $(MOC) include/rksetsys.h
	$(MOC) include/rksetsys.h -o include/moc_rksetsys.cpp

include/moc_rksetvar.cpp: $(MOC) include/rksetvar.h
	$(MOC) include/rksetvar.h -o include/moc_rksetvar.cpp

include/moc_rktabwgt.cpp: $(MOC) include/rktabwgt.h
	$(MOC) include/rktabwgt.h -o include/moc_rktabwgt.cpp

include/moc_rktrdmnt.cpp: $(MOC) include/rktrdmnt.h
	$(MOC) include/rktrdmnt.h -o include/moc_rktrdmnt.cpp

include/moc_rktrdmsg.cpp: $(MOC) include/rktrdmsg.h
	$(MOC) include/rktrdmsg.h -o include/moc_rktrdmsg.cpp

ui/moc_rkmsgview.cpp: $(MOC) ui/rkmsgview.h
	$(MOC) ui/rkmsgview.h -o ui/moc_rkmsgview.cpp

####### Install

install:  

uninstall:  

